### ISSUE TITLE
Types property can now handle multiple types

### ISSUE THREAD

**Issue by amonteils** [amonteils/openapi_parser#4]
Context:
Types can now be an array of types. There is also a new type available which is null. [spec](https://swagger.io/docs/specification/data-models/data-types/)

Example
```
parameters:
  - name: friendly-label
    in: query
    schema:
      type:
        - string
        - 'null'
```
